### ISSUE TITLE
~/.tabby-client/config.toml not working as expected

### ISSUE THREAD

**Issue by nic-avant** [TabbyML/vim-tabby#1]
I have been playing with Tabby from Neovim, and up until today have been specifying my endpoint url in my vim config with a line like this: `vim.g.tabby_server_url = "http://0.0.0.0:8088"`. I see the docs now say to put this in `~/.tabby-client/agent-config.toml` in a `[server]` key like this:
```toml
[server]
endpoint = "http://0.0.0.0:8088" 
```

But `:Tabby status` now says "cannot connect to server"

I'm not sure how to get much more feedback from `tabby` via logs or anything so I'll try to provide anything helpful with some instruction!

Thanks!

**Comment by wsxiaoys** [comment]
Hi - there's a mistake on 1.0.0 documentation (which has been fixed in 1.0.1). The correct path of config.toml should be `~/.tabby-client/agent/config.toml`

https://github.com/TabbyML/vim-tabby/commit/5430bcc44144fa362787b6629d2c39016dad7a32#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

**Comment by nic-avant** [comment]
Thanks for the quick response - my issue actually had a typo. I do have my config in `~/.tabby-client/agent/config.toml` but `:Tabby status` still showing "cannot connect to server". I've upgraded Tabby to 0.3.1 via `brew` and it works if I keep my vim setting as originally stated...

I'm on Mac if that matters, but I'd figure this is specific to an editor, not the hardware

**Comment by wsxiaoys** [comment]
Could you confirm your vim extension version and try v1.0.1 if possible?

Otherwise, please follow https://tabby.tabbyml.com/docs/extensions/troubleshooting#cannot-connect-to-tabby-server and share the error log from agent

**Comment by nic-avant** [comment]
Ope you got me - had to update the client!
